version: "3"
services:
  db:
    image: rethinkdb
    ports:
      - "28015:28015"
      - "8080:8080"
    volumes:
      - ./data:/data

  api:
    build: ./backend
    volumes:
      - ./backend:/usr/src/service
      - ./backend/images:/usr/src/service/images
      - /usr/src/service/node_modules
    working_dir: /usr/src/service
    ports:
      - "3030:3030"
    depends_on:
      - db
      - redis
    environment:
      WAIT_HOSTS: db:28015

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/codewar.access.log:/etc/nginx/log/codewar.access.log
    depends_on:
      # - frontend
      - api

  redis:
    image: "redis:4-alpine"
    command: redis-server --requirepass h7nVvFfG6F5U7SjmPmEWjDXHJrsjyUpq
    ports:
      - "6379:6379"
